version: '3.8'

services:
  test-container:
    image: nginx:alpine
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 1s
      retries: 3
    ports:
      - "8080:80" 